### ISSUE TITLE
Provide translations

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/WeatherVenue#28]
At this moment, the code is well decoupled so that someone with minimal JavaScript skills can understand how it works.
I mean, I did not use external files or any other localization library, it's all implemented in plain JavaScript (dictionaries, functions, switch case blocks ...).

We have English and Arabic, but we need more. Spanish, Dutch, Chinese, Japanese and any other tongue is welcome.

**Comment by aditisingh2412** [comment]
Hey, I'm a newbie :) Can I work on this?

**Comment by bacloud14** [comment]
hello @aditisingh2412 . Sure. However project evolved from it's initial versions. Tell me if you could install it on local then I assign this to you.

**Comment by aditisingh2412** [comment]
We have to provide translation in accessibility.js?

**Comment by bacloud14** [comment]
no, now it's in 
https://github.com/bacloud14/WeatherVenue/blob/master/src/js/lang_mappings.js
and 
https://github.com/bacloud14/WeatherVenue/blob/master/helpers.js

Adding a new language is not that easy, but we can add more languages in these, but to make them visible, there are more tweaks in UI and also back end.

**Comment by bacloud14** [comment]
You can work on these two files only. If you get how variables are propagated between back and front, you can go for it too. Otherwise I do it.

**Comment by aditisingh2412** [comment]
Ok, I'll look into it :)

**Comment by JoseBorbon** [comment]
hey bacloud, I am working on the set up locally so that I can work on Spanish translations. I managed to get up to the last API key.

The last bullet point says if I plan to make changes to those files then I must run those commands?

Also for gulp version_dependencies I tried to run that and it kept giving me

Error [ERR_REQUIRE_ESM]: require() of ES Module, Instead change the require of index.js to a dynamic import() which is available in all CommonJS modules.

Also, I did notice there is no indexHTML file. I did see ejs files though. I wanted to know what I could do to preview the app page with live server or if I would need to use something else.

**Comment by bacloud14** [comment]
Thank you for contributing to this 😃 

3- Index files are here: https://github.com/bacloud14/WeatherVenue/tree/master/views 
I didn't use a translation library so that text is provided in JSON files or something separate, it is simply a replica of Index files for different languages.

2- Now back to the error, Check this [thread](https://stackoverflow.com/questions/57169793/error-err-require-esm-how-to-use-es6-modules-in-node-12)
I cannot help longer as I didn't encounter the error.

1- Yes, whenever you change a [client](https://github.com/bacloud14/WeatherVenue/tree/master/src/js) JS file; You need to run 
: `gulp clean` then `gulp compress_js` and `gulp version_dependencies`.

**Comment by bryandms** [comment]
Hi @bacloud14 👋🏼
I suggest that you make a `lang` folder in the project where you create a file per language and an `index.js` where each of these files is exported.

E.g.
```js
// lang/en.lang.js
module.exports = {
  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  aqi: {
    1: 'Air quality: Good',
    2: 'Air quality: Fair',
    3: 'Air quality: Moderate',
    4: 'Air quality: Poor',
    5: 'Air quality: Very Poor'
  },
  pictures: {
    success: (place) => `Local pictures of ${place}`,
    fail: (place) => `There are no pictures found for ${place}`
  },
  notFoundMessages:{
    h1: 'Oops!',
    h2: 'Page is not found',
    details: 'Sorry, an error has occured or the requested page is not found.',
    actions: 'Take me home'
  },
  tour: {
    map: '"Interact with the map. You can click on markers and see each city weather cards. Right click on two markers to reveal a directions link. Also drag days control to see how tempreture will be in the next days."',
    cards: '"You can drag cards to the weather comparisons area. Colored cards reflect maximum and minimum temperature in one day. Click on min-max to simplify comparisions visually."',
    comparision: '"In comparison area You can see cards of different days and of different cities too. For Android devices and on Google Chrome only, You can also share any card with people."',
    gallery: '"A beautiful local gallery of pictures of the main city."'
  },
}

// lang/index.js
module.exports = {
  en: require('./en.lang.js'),
  // Other languages
}

// WeatherVenue/src/js/lang_mappings.js
const lang = require('./lang/index.js')

function _weekdaysLangs(language) {
  switch (language) {
    case 'en':
      return lang.en.weekdays
  // More code...
}
```

This is easier to maintain when you have many languages and need to make a change. If you want to make the suggestion let me know and I can do the refactor.

**Comment by bacloud14** [comment]
Hello @bryandms,

Thank you for your suggestion, it seems cleaner for me.
Also thanks for reviewing https://github.com/bacloud14/WeatherVenue/blob/17234d753d00c6d5c05e15793abbe434675a8763/helpers.js#L90
We need to through client side also though
https://github.com/bacloud14/WeatherVenue/blob/master/src/js/lang_mappings.js
I was thinking of using the same internationalization library like I used in a later project (always learning) where I used **i18next** (there are many).

This issue was about simply providing a new translation even if hard coded. Nevertheless If you wish to add a new language Spanish I guess 😃 I 'm more than happy. Meanwhile you can implement the cleaner version as you suggested.

Thanks !

**Comment by bacloud14** [comment]
If not, I will rework translations but later as I'm on another project for now.
Thanks anyway 😃

**Comment by bryandms** [comment]
Great, I'm going to work on it.

**Comment by bacloud14** [comment]
Thanks @bryandms good luck
